spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8181/realms/reverse-auction-spring
    cloud:
        gateway:
          routes:
              - id: discovery-server
                uri: http://localhost:8761
                predicates:
                  - Path=/eureka/web
              - id: bid-service
                uri: http://localhost:53977
                predicates:
                  - Path=/bid/**
              - id: product-service
                uri: http://localhost:53978
                predicates:
                  - Path=/product/**
              - id: httpbin
                uri: http://httpbin.org
                predicates:
                  - Path=/anything/**
                filters:
                  - AddRequestHeader=X-Some-Header, GatewayTest
                  - AddResponseHeader=X-Some-Header, GatewayTestResponse


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8085

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
    org.springframework.cloud.gateway: DEBUG





        